name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Release Binary
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set up Go 1.22.3
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'

    - name: Build binary
      run: |
        export GOOS=linux
        export GOARCH=amd64
        go build -o myproject-${GOOS}-${GOARCH} .

    - name: Upload Release Binary
      uses: actions/upload-artifact@v2
      with:
        name: myproject-linux-amd64
        path: myproject-linux-amd64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Binary
      uses: actions/download-artifact@v2
      with:
        name: myproject-linux-amd64
        path: release

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/myproject-linux-amd64
        token: ${{ secrets.GITHUB_TOKEN }}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
